/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.JFrame;

/**
 *
 * @author Jatendar
 */
public class simpleCalculator extends javax.swing.JFrame {

    /**
     * Creates new form simpleCalculator
     */
    public simpleCalculator() {
        initComponents();
        onRadio.setEnabled(false);
    }
    double ans, num;
    int calculator;

    public void operation() {
        switch (calculator) {
            case 1: // for addition
                ans = num + Double.parseDouble(textField.getText());
                textField.setText(Double.toString(ans));
                break;
            case 2: // for sub;
                ans = num - Double.parseDouble(textField.getText());
                textField.setText(Double.toString(ans));
                break;
            case 3: // for multiplication
                ans = num * Double.parseDouble(textField.getText());
                textField.setText(Double.toString(ans));
                break;
            case 4: // for division
                ans = num / Double.parseDouble(textField.getText());
                textField.setText(Double.toString(ans));
                break;
            
        }
    }

    public void enable() {
        textField.setEnabled(true);
        onRadio.setEnabled(false);
        offRadio.setEnabled(true);
        acosButton.setEnabled(true);
        addButton.setEnabled(true);
        asinButton.setEnabled(true);
        oneButton.setEnabled(true);
        twoButton.setEnabled(true);
        threeButton.setEnabled(true);
        fourButton.setEnabled(true);
        fiveButton.setEnabled(true);
        sixButton.setEnabled(true);
        sevenButton.setEnabled(true);
        eigthButton.setEnabled(true);
        nineButton.setEnabled(true);
        zeroButton.setEnabled(true);
        pointButton.setEnabled(true);
        clearButton.setEnabled(true);
        subButton.setEnabled(true);
        multiButton.setEnabled(true);
        divButton.setEnabled(true);
        equalButton.setEnabled(true);
        expButton.setEnabled(true);
        rootButton.setEnabled(true);
        squareButton.setEnabled(true);
        cubeButton.setEnabled(true);
        atanButton.setEnabled(true);
        acosButton.setEnabled(true);
        sinButton.setEnabled(true);
        cosButton.setEnabled(true);
        tanButton.setEnabled(true);
        nButton.setEnabled(true);
        logButton.setEnabled(true);
        lnButton.setEnabled(true);
        piButton.setEnabled(true);
        perButton.setEnabled(true);
    }

    public void disable() {
        
        textField.setEnabled(false);
        onRadio.setEnabled(true);
        offRadio.setEnabled(false);
        acosButton.setEnabled(false);
        addButton.setEnabled(false);
        asinButton.setEnabled(false);
        oneButton.setEnabled(false);
        twoButton.setEnabled(false);
        threeButton.setEnabled(false);
        fourButton.setEnabled(false);
        fiveButton.setEnabled(false);
        sixButton.setEnabled(false);
        sevenButton.setEnabled(false);
        eigthButton.setEnabled(false);
        nineButton.setEnabled(false);
        zeroButton.setEnabled(false);
        pointButton.setEnabled(false);
        clearButton.setEnabled(false);
        subButton.setEnabled(false);
        multiButton.setEnabled(false);
        divButton.setEnabled(false);
        equalButton.setEnabled(false);
        expButton.setEnabled(false);
        rootButton.setEnabled(false);
        squareButton.setEnabled(false);
        cubeButton.setEnabled(false);
        atanButton.setEnabled(false);
        acosButton.setEnabled(false);
        sinButton.setEnabled(false);
        cosButton.setEnabled(false);
        tanButton.setEnabled(false);
        nButton.setEnabled(false);
        logButton.setEnabled(false);
        lnButton.setEnabled(false);
        piButton.setEnabled(false);
        perButton.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton5 = new javax.swing.JButton();
        textField = new javax.swing.JTextField();
        onRadio = new javax.swing.JRadioButton();
        offRadio = new javax.swing.JRadioButton();
        clearButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        sevenButton = new javax.swing.JButton();
        eigthButton = new javax.swing.JButton();
        nineButton = new javax.swing.JButton();
        subButton = new javax.swing.JButton();
        fourButton = new javax.swing.JButton();
        fiveButton = new javax.swing.JButton();
        sixButton = new javax.swing.JButton();
        multiButton = new javax.swing.JButton();
        oneButton = new javax.swing.JButton();
        twoButton = new javax.swing.JButton();
        threeButton = new javax.swing.JButton();
        divButton = new javax.swing.JButton();
        zeroButton = new javax.swing.JButton();
        pointButton = new javax.swing.JButton();
        equalButton = new javax.swing.JButton();
        lable = new javax.swing.JLabel();
        squareButton = new javax.swing.JButton();
        sinButton = new javax.swing.JButton();
        cosButton = new javax.swing.JButton();
        tanButton = new javax.swing.JButton();
        rootButton = new javax.swing.JButton();
        cubeButton = new javax.swing.JButton();
        asinButton = new javax.swing.JButton();
        atanButton = new javax.swing.JButton();
        acosButton = new javax.swing.JButton();
        expButton = new javax.swing.JButton();
        nButton = new javax.swing.JButton();
        logButton = new javax.swing.JButton();
        lnButton = new javax.swing.JButton();
        perButton = new javax.swing.JButton();
        piButton = new javax.swing.JButton();

        jButton5.setText("jButton5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        textField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        buttonGroup1.add(onRadio);
        onRadio.setText("On");
        onRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onRadioActionPerformed(evt);
            }
        });

        buttonGroup1.add(offRadio);
        offRadio.setText("off");
        offRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                offRadioActionPerformed(evt);
            }
        });

        clearButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        clearButton.setText("C");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        addButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addButton.setText("+");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        sevenButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sevenButton.setText("7");
        sevenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenButtonActionPerformed(evt);
            }
        });

        eigthButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        eigthButton.setText("8");
        eigthButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eigthButtonActionPerformed(evt);
            }
        });

        nineButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nineButton.setText("9");
        nineButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nineButtonActionPerformed(evt);
            }
        });

        subButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        subButton.setText("-");
        subButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subButtonActionPerformed(evt);
            }
        });

        fourButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fourButton.setText("4");
        fourButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourButtonActionPerformed(evt);
            }
        });

        fiveButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fiveButton.setText("5");
        fiveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveButtonActionPerformed(evt);
            }
        });

        sixButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sixButton.setText("6");
        sixButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixButtonActionPerformed(evt);
            }
        });

        multiButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        multiButton.setText("*");
        multiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiButtonActionPerformed(evt);
            }
        });

        oneButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        oneButton.setText("1");
        oneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneButtonActionPerformed(evt);
            }
        });

        twoButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        twoButton.setText("2");
        twoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoButtonActionPerformed(evt);
            }
        });

        threeButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        threeButton.setText("3");
        threeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeButtonActionPerformed(evt);
            }
        });

        divButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        divButton.setText("/");
        divButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divButtonActionPerformed(evt);
            }
        });

        zeroButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        zeroButton.setText("0");
        zeroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroButtonActionPerformed(evt);
            }
        });

        pointButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pointButton.setText(".");
        pointButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pointButtonActionPerformed(evt);
            }
        });

        equalButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        equalButton.setText("=");
        equalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalButtonActionPerformed(evt);
            }
        });

        lable.setForeground(new java.awt.Color(255, 51, 51));

        squareButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        squareButton.setText("x2");
        squareButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                squareButtonActionPerformed(evt);
            }
        });

        sinButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sinButton.setText("sin");
        sinButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sinButtonActionPerformed(evt);
            }
        });

        cosButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cosButton.setText("cos");
        cosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cosButtonActionPerformed(evt);
            }
        });

        tanButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tanButton.setText("tan");
        tanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanButtonActionPerformed(evt);
            }
        });

        rootButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rootButton.setText("√x");
        rootButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rootButtonActionPerformed(evt);
            }
        });

        cubeButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cubeButton.setText("x3");
        cubeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cubeButtonActionPerformed(evt);
            }
        });

        asinButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        asinButton.setText("asin");
        asinButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asinButtonActionPerformed(evt);
            }
        });

        atanButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        atanButton.setText("atan");
        atanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atanButtonActionPerformed(evt);
            }
        });

        acosButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        acosButton.setText("acos");
        acosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acosButtonActionPerformed(evt);
            }
        });

        expButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        expButton.setText("Exp");
        expButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expButtonActionPerformed(evt);
            }
        });

        nButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nButton.setText("n!");
        nButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nButtonActionPerformed(evt);
            }
        });

        logButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        logButton.setText("log");
        logButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logButtonActionPerformed(evt);
            }
        });

        lnButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lnButton.setText("ln");
        lnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnButtonActionPerformed(evt);
            }
        });

        perButton.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        perButton.setText("10^");
        perButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perButtonActionPerformed(evt);
            }
        });

        piButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        piButton.setText("PI");
        piButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                piButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lable, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(textField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(oneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(twoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(fourButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(fiveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(sevenButton, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                                                    .addComponent(onRadio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                                                    .addComponent(offRadio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(eigthButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(nineButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(sixButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(threeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(subButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(multiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(divButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cosButton)
                                            .addComponent(tanButton)
                                            .addComponent(sinButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(squareButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(zeroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pointButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rootButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(expButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(perButton, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(equalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(atanButton)
                                            .addComponent(acosButton)
                                            .addComponent(asinButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cubeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(nButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(logButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(lnButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(piButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lable, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(textField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(onRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(offRadio))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(squareButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(nButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cubeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(eigthButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sevenButton, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(nineButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(subButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sinButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(asinButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fourButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fiveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sixButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(multiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cosButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(acosButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(divButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(threeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(twoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(oneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(atanButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(piButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(perButton, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(expButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rootButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pointButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(zeroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(equalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void eigthButtonActionPerformed(java.awt.event.ActionEvent evt) {                                            
        textField.setText(textField.getText() + "8");
    }                                           

    private void oneButtonActionPerformed(java.awt.event.ActionEvent evt) {                                          
        textField.setText(textField.getText() + "1");
    }                                         

    private void twoButtonActionPerformed(java.awt.event.ActionEvent evt) {                                          
        textField.setText(textField.getText() + "2");
    }                                         

    private void threeButtonActionPerformed(java.awt.event.ActionEvent evt) {                                            
        textField.setText(textField.getText() + "3");
    }                                           

    private void fourButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
        textField.setText(textField.getText() + "4");
    }                                          

    private void fiveButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
        textField.setText(textField.getText() + "5");
    }                                          

    private void sixButtonActionPerformed(java.awt.event.ActionEvent evt) {                                          
        textField.setText(textField.getText() + "6");
    }                                         

    private void sevenButtonActionPerformed(java.awt.event.ActionEvent evt) {                                            
        textField.setText(textField.getText() + "7");
    }                                           

    private void nineButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
        textField.setText(textField.getText() + "9");
    }                                          

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {                                            
        textField.setText("");
    }                                           

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {                                          
        
        num = Double.parseDouble(textField.getText());
        calculator = 1;
        textField.setText("");
        lable.setText(num + "+");
    }                                         

    private void subButtonActionPerformed(java.awt.event.ActionEvent evt) {                                          
        num = Double.parseDouble(textField.getText());
        calculator = 2;
        textField.setText("");
        lable.setText(num + "-");
    }                                         

    private void multiButtonActionPerformed(java.awt.event.ActionEvent evt) {                                            
        num = Double.parseDouble(textField.getText());
        calculator = 3;
        textField.setText("");
        lable.setText(num + "*");
    }                                           

    private void divButtonActionPerformed(java.awt.event.ActionEvent evt) {                                          
        num = Double.parseDouble(textField.getText());
        calculator = 4;
        textField.setText("");
        lable.setText(num + "/");
    }                                         

    private void equalButtonActionPerformed(java.awt.event.ActionEvent evt) {                                            
        operation();
        lable.setText("");
    }                                           

    private void pointButtonActionPerformed(java.awt.event.ActionEvent evt) {                                            
        textField.setText(textField.getText() + ".");
    }                                           

    private void zeroButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
        textField.setText(textField.getText() + "0");
    }                                          

    private void squareButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             
        num = Double.parseDouble(textField.getText());
        ans = Math.pow(Double.parseDouble(textField.getText()), 2);
        textField.setText(Double.toString(ans));
    }                                            

    private void sinButtonActionPerformed(java.awt.event.ActionEvent evt) {                                          
        num = Double.parseDouble(textField.getText());
        ans = Math.sin(Double.parseDouble(textField.getText()));
        textField.setText(Double.toString(ans));
    }                                         

    private void cosButtonActionPerformed(java.awt.event.ActionEvent evt) {                                          
        num = Double.parseDouble(textField.getText());
        ans = Math.cos(Double.parseDouble(textField.getText()));
        textField.setText(Double.toString(ans));
    }                                         

    private void tanButtonActionPerformed(java.awt.event.ActionEvent evt) {                                          
        num = Double.parseDouble(textField.getText());
        ans = Math.tan(Double.parseDouble(textField.getText()));
        textField.setText(Double.toString(ans));
    }                                         

    private void rootButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
        num = Double.parseDouble(textField.getText());
        ans = Math.sqrt(Double.parseDouble(textField.getText()));
        textField.setText(Double.toString(ans));
    }                                          

    private void cubeButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
        num = Double.parseDouble(textField.getText());
        ans = Math.pow(Double.parseDouble(textField.getText()), 3);
        textField.setText(Double.toString(ans));
    }                                          

    private void expButtonActionPerformed(java.awt.event.ActionEvent evt) {                                          
        num = Double.parseDouble(textField.getText());
        Math.exp(Double.parseDouble(textField.getText()));
        textField.setText(Double.toString(ans));
    }                                         

    private void acosButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
        num = Double.parseDouble(textField.getText());
        ans = Math.acos(Double.parseDouble(textField.getText()));
        textField.setText(Double.toString(ans));
    }                                          

    private void asinButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
        num = Double.parseDouble(textField.getText());
        ans = Math.asin(Double.parseDouble(textField.getText()));
        textField.setText(Double.toString(ans));
    }                                          

    private void atanButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
        num = Double.parseDouble(textField.getText());
        ans = Math.atan(Double.parseDouble(textField.getText()));
        textField.setText(Double.toString(ans));
        
    }                                          

    private void offRadioActionPerformed(java.awt.event.ActionEvent evt) {                                         
        disable();
    }                                        

    private void onRadioActionPerformed(java.awt.event.ActionEvent evt) {                                        
        enable();
    }                                       

    private void nButtonActionPerformed(java.awt.event.ActionEvent evt) {                                        
        double number = 1;
        for (int i = 1; i <= Double.parseDouble(textField.getText()); i++) {
            number = number * i;
        }
        textField.setText(Double.toString(number));
    }                                       

    private void logButtonActionPerformed(java.awt.event.ActionEvent evt) {                                          
        num = Double.parseDouble(textField.getText());
        ans = Math.log10(Double.parseDouble(textField.getText()));
        textField.setText(Double.toString(ans));
    }                                         

    private void lnButtonActionPerformed(java.awt.event.ActionEvent evt) {                                         
        num = Double.parseDouble(textField.getText());
        ans = Math.log(Double.parseDouble(textField.getText()));
        textField.setText(Double.toString(ans));
    }                                        

    private void piButtonActionPerformed(java.awt.event.ActionEvent evt) {                                         
        ans = 3.14 * Double.parseDouble(textField.getText());
        textField.setText(Double.toString(ans));
    }                                        

    private void perButtonActionPerformed(java.awt.event.ActionEvent evt) {                                          
        num = Double.parseDouble(textField.getText());
        ans = Math.pow(Double.parseDouble(textField.getText()), 10);
        textField.setText(Double.toString(ans));
    }                                         

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(simpleCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(simpleCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(simpleCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(simpleCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new simpleCalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton acosButton;
    private javax.swing.JButton addButton;
    private javax.swing.JButton asinButton;
    private javax.swing.JButton atanButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton cosButton;
    private javax.swing.JButton cubeButton;
    private javax.swing.JButton divButton;
    private javax.swing.JButton eigthButton;
    private javax.swing.JButton equalButton;
    private javax.swing.JButton expButton;
    private javax.swing.JButton fiveButton;
    private javax.swing.JButton fourButton;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel lable;
    private javax.swing.JButton lnButton;
    private javax.swing.JButton logButton;
    private javax.swing.JButton multiButton;
    private javax.swing.JButton nButton;
    private javax.swing.JButton nineButton;
    private javax.swing.JRadioButton offRadio;
    private javax.swing.JRadioButton onRadio;
    private javax.swing.JButton oneButton;
    private javax.swing.JButton perButton;
    private javax.swing.JButton piButton;
    private javax.swing.JButton pointButton;
    private javax.swing.JButton rootButton;
    private javax.swing.JButton sevenButton;
    private javax.swing.JButton sinButton;
    private javax.swing.JButton sixButton;
    private javax.swing.JButton squareButton;
    private javax.swing.JButton subButton;
    private javax.swing.JButton tanButton;
    private javax.swing.JTextField textField;
    private javax.swing.JButton threeButton;
    private javax.swing.JButton twoButton;
    private javax.swing.JButton zeroButton;
    // End of variables declaration                   
}
